# Site settings
title: Swayam Prakash Panda
description: Data Analyst | AI/ML Enthusiast | B.Tech CSE (AIML) Student
url: "https://swayam200.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

# Custom variables
author:
  name: Swayam Prakash Panda
  email: swayam.panda200@gmail.com
  linkedin: swayam200
  github: swayam200

# GitHub Pages specific
github_username: swayam200